"""TwinCAT FBD/FUP to ST migration."""
from __future__ import annotations

from migrator.codegen import (
    _apply_input_flag,
    _check_type_mismatch,
    _clean_bool_expr,
    _gen_assign,
    _gen_bool_expression,
    _gen_expression,
    _gen_fb_call,
    _gen_fb_inline_expr,
    _gen_function_call_expr,
    _gen_iec_func,
    _gen_infix_op,
    _gen_operator_call,
    _gen_sel,
    _gen_top_level_box,
    _gen_unknown_box,
    _generate_network_code,
    _is_default_skip,
    _is_fully_wrapped,
    _is_return_assign,
    convert_networks_to_st,
)
from migrator.constants import (
    ARITHMETIC_OPS,
    COMPARISON_OPS,
    CONVERSION_FUNCS,
    FB_CALL_TYPES,
    IEC_FUNCTIONS,
    INFIX_OPERATORS,
    SCRIPT_VERSION,
    SUPPORTED_EXTENSIONS,
)
from migrator.fbd.parser import _parse_st_snippet, parse_nwl_networks
from migrator.fbd.pipeline import FBD_SOURCE_TYPE, FBD_TOOL_NAME, main, process_file
from migrator.fbd.xml_patch import write_st_to_xml
from migrator.cli import load_config, parse_arguments
from migrator.io_utils import (
    _resolve_output_path,
    can_replace,
    collect_input_files,
    create_backup,
    write_output_file,
)
from migrator.reporting import (
    MigrationLogger,
    MigrationReport,
    _final_checklist,
    _print_analysis,
    _print_dry_run,
)
from migrator.types import (
    ActionInfo,
    AssignNode,
    BoxNode,
    DemuxNode,
    MigrationConfig,
    NwlNetwork,
    OperandNode,
    StNetwork,
    TcFile,
)
from migrator.validation import (
    _collect_vars,
    _collect_vars_node,
    build_generated_header,
    calculate_accuracy,
    validate_generated_st,
)
from migrator.xml_reader import (
    _detect_impl_type,
    _detect_pou_type,
    _find_child_by_name,
    _find_v,
    _get_v_str,
    _regenerate_guids,
    _strip_quotes,
    load_file,
)

__all__ = [
    "FBD_SOURCE_TYPE",
    "FBD_TOOL_NAME",
    "main",
    "process_file",
    "parse_nwl_networks",
    "write_st_to_xml",
    "_parse_st_snippet",
    # IR classes
    "ActionInfo",
    "AssignNode",
    "BoxNode",
    "DemuxNode",
    "MigrationConfig",
    "MigrationLogger",
    "MigrationReport",
    "NwlNetwork",
    "OperandNode",
    "StNetwork",
    "TcFile",
    # Constants
    "ARITHMETIC_OPS",
    "COMPARISON_OPS",
    "CONVERSION_FUNCS",
    "FB_CALL_TYPES",
    "IEC_FUNCTIONS",
    "INFIX_OPERATORS",
    "SCRIPT_VERSION",
    "SUPPORTED_EXTENSIONS",
    # Public functions
    "build_generated_header",
    "calculate_accuracy",
    "can_replace",
    "collect_input_files",
    "convert_networks_to_st",
    "create_backup",
    "load_config",
    "load_file",
    "parse_arguments",
    "validate_generated_st",
    "write_output_file",
    # Private XML helpers
    "_detect_impl_type",
    "_detect_pou_type",
    "_find_child_by_name",
    "_find_v",
    "_get_v_str",
    "_strip_quotes",
    # Private codegen
    "_apply_input_flag",
    "_check_type_mismatch",
    "_clean_bool_expr",
    "_collect_vars",
    "_collect_vars_node",
    "_final_checklist",
    "_gen_assign",
    "_gen_bool_expression",
    "_gen_expression",
    "_gen_fb_call",
    "_gen_fb_inline_expr",
    "_gen_function_call_expr",
    "_gen_iec_func",
    "_gen_infix_op",
    "_gen_operator_call",
    "_gen_sel",
    "_gen_top_level_box",
    "_gen_unknown_box",
    "_generate_network_code",
    "_is_default_skip",
    "_is_fully_wrapped",
    "_is_return_assign",
    # Private pipeline helpers
    "_print_analysis",
    "_print_dry_run",
    "_regenerate_guids",
    "_resolve_output_path",
]
