<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="PRG_Syntax_Main" Id="{c1891f57-0da9-4e5c-b324-15acd7b61c68}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Syntax_Main
VAR
    _nCycle : UDINT;
    _bReady : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_nCycle := _nCycle + 1;
_bReady := TRUE;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>