<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_Syntax_QueryInterface" Id="{079481bb-92ae-48cd-b4b5-6c82d3a4bbfc}" SpecialFunc="None">
    <Declaration><![CDATA[function_block FB_Syntax_QueryInterface
var
    ipWidget : I_Syntax_Widget;
    ipExtended : I_Syntax_Extended;
    fbDerived : FB_Syntax_Derived;
    bHasExtended : bool;
    bQuerySuccess : bool;
    hrResult : hresult;
end_var
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ipWidget := fbDerived;


if ipWidget <> 0 then
    bQuerySuccess := __QUERYINTERFACE(ipWidget, ipExtended);
    if bQuerySuccess and (ipExtended <> 0) then
        bHasExtended := ipExtended.M_Execute(nCommand := 1);
    end_if
end_if
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>