<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_Syntax_IfMultilineCalls" Id="{5b203008-c657-4a7f-a331-701f05bebd84}" SpecialFunc="None">
    <Declaration><![CDATA[function_block FB_Syntax_IfMultilineCalls
var  
    sStr1   : string(80);  
    sStr2   : string(80);  
    sResult : string(255);  
    rTarget : reference to int;  
    nVal    : int;  
    bOk     : bool;  
end_var
]]></Declaration>
    <Implementation>
      <ST><![CDATA[if len(sStr1) > 0 and len(sStr2) > 0 then  
    bOk := false;  
else  
    bOk := true;
end_if  


if not __ISVALIDREF(rTarget) then
    nVal := 0;
else  
    nVal := rTarget;
end_if


if (len(sStr1) > 0)
    and (len(sStr2) > 0)
    and (len(sResult) = 0)
then  
    bOk := true;  
end_if  
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>