<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_Syntax_ComplexInits" Id="{f0f30913-64fc-494b-96dc-21b3e5cc2923}" SpecialFunc="None">
    <Declaration><![CDATA[function_block FB_Syntax_ComplexInits
var
    stConfig : ST_Syntax_Mini := (nId := 10, bActive := true, sName := 'InitTag');
    aNumbers : array[1..5] of int := [10, 20, 30, 40, 50];
    aStructs : array[1..2] of ST_Syntax_Mini := [(nId := 1, bActive := false, sName := 'First'), (nId := 2, bActive := true, sName := 'Second')];
    a2D : array[1..2, 1..2] of int := [1, 2, 3, 4];
end_var
]]></Declaration>
    <Implementation>
      <ST><![CDATA[if stConfig.nId = 10 then
    stConfig.nId := 20;
    stConfig.bActive := false;
    stConfig.sName := 'UpdatedTag';
end_if
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>